version: 2.1

orbs:
  python: circleci/python@1.5.0
jobs:
  build:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip

workflows:
  sample:
    jobs:
      ## For any Branch
      - build

      ## For Including Specific Branches
      ## References: https://circleci.com/docs/2.0/configuration-reference#branches
      #- build:
       #   filters:
        #    branches:
         #     only:
          #      - main
           #     - release
           #     - /xyz.*/ ## Regex

      ## For Ignoring Specific Branches
      ## Reference: https://circleci.com/docs/2.0/configuration-reference#example-full-configuration
      #- build:
       #   filters:
        #    branches:
         #     ignore:
          #      - development
           #     - /feature-.*/ ## Regex
